language: rust
os: linux
dist: focal

cache:
  - cargo

rust:
  - stable

before_script:
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/mdbook || cargo install mdbook --no-default-features --vers "^0.4.7")
  - cargo install-update -a

script:
  - python3 tools/generate_summary.py
  - mdbook build
  - python3 tools/fix_dollar_sign.py

deploy:
  provider: pages
  strategy: git
  edge: true
  cleanup: false
  github-token: $GITHUB_TOKEN
  local-dir: book
  keep-history: false
  on:
    branch: main
  target_branch: gh-pages