[book]
authors = ["Guilherme de Lyra", "Max Henrique"]
language = "pt-br"
multilingual = false
src = "src"
title = "Conceitos de Engenharia de Software aplicados"

[preprocessor.count_time]
command = "python3 tools/count_estimated_time.py"
renderer = ["html"]

[output.html]
default-theme = "rust"
copy-fonts = true
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/appointment-octopus/ebook"
