name: Continuous integration
on: [push]

jobs:
  build_and_deploy:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
            python-version: 3.8

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
    
      - name: Install mdBook
        run: cargo install mdbook --no-default-features --vers "^0.4.7"

      - name: Build book
        run: |
            python3 tools/generate_summary.py
            mdbook build
            python3 tools/fix_dollar_sign.py

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./book
